sylius_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: sylius_backend.controller.dashboard:mainAction }

sylius_backend_pigalle_slide:
    resource: @SyliusBackendBundle/Resources/config/routing/pigalle_slide.yml
    prefix: /slider
 
sylius_backend_pigalle_local:
    resource: @SyliusBackendBundle/Resources/config/routing/pigalle_local.yml
    prefix: /locales
       
sylius_backend_user:
    resource: @SyliusBackendBundle/Resources/config/routing/user.yml
    prefix: /users

sylius_backend_product:
    resource: @SyliusBackendBundle/Resources/config/routing/product.yml
    prefix: /products

sylius_backend_product_collection:
    resource: @SyliusBackendBundle/Resources/config/routing/product_collection.yml
    prefix: /product-collections
    
#sylius_backend_stockable:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/stockable.yml
#    prefix: /stockables

sylius_backend_variant:
    resource: @SyliusBackendBundle/Resources/config/routing/variant.yml
    prefix: /products/{productId}/variants

sylius_backend_option:
    resource: @SyliusBackendBundle/Resources/config/routing/option.yml
    prefix: /options

#sylius_backend_property:
#    resource: @SyliusBackendBundle/Resources/config/routing/property.yml
#    prefix: /properties

#sylius_backend_prototype:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/prototype.yml
#    prefix: /prototypes

sylius_backend_taxonomy:
    resource: @SyliusBackendBundle/Resources/config/routing/taxonomy.yml
    prefix: /taxonomies

sylius_backend_taxon:
    resource: @SyliusBackendBundle/Resources/config/routing/taxon.yml
    prefix: /taxonomies/{taxonomyId}/taxon

sylius_backend_order:
    resource: @SyliusBackendBundle/Resources/config/routing/order.yml
    prefix: /orders

sylius_backend_promotion:
    resource: @SyliusBackendBundle/Resources/config/routing/promotion.yml
    prefix: /promotions

sylius_backend_promotion_rule:
    resource: @SyliusBackendBundle/Resources/config/routing/promotion_rule.yml
    prefix: /promotion-rules

sylius_backend_promotion_action:
    resource: @SyliusBackendBundle/Resources/config/routing/promotion_action.yml
    prefix: /promotion-actions

#sylius_backend_tax_category:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_category.yml
#    prefix: /tax-categories

#sylius_backend_tax_rate:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_rate.yml
#    prefix: /tax-rates

#sylius_backend_shipping_category:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/shipping_category.yml
#    prefix: /shipping-categories

#sylius_backend_shipping_method:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/shipping_method.yml
#    prefix: /shipping-methods

sylius_backend_shipment:
    resource: @SyliusBackendBundle/Resources/config/routing/shipment.yml
    prefix: /shipments

#sylius_backend_payment_method:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/payment_method.yml
#    prefix: /payment-methods

sylius_backend_payment:
    resource: @SyliusBackendBundle/Resources/config/routing/payment.yml
    prefix: /payments

#sylius_backend_country:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/country.yml
#    prefix: /countries

#sylius_backend_province:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/province.yml
#    prefix: /provinces

#sylius_backend_zone:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/zone.yml
#    prefix: /zones

#sylius_backend_zone_member:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/zone_member.yml
#    prefix: /zone-members

sylius_backend_settings:
    resource: @SyliusBackendBundle/Resources/config/routing/settings.yml
    prefix: /settings

#sylius_backend_security:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/security.yml