sylius_backend_option_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.option:indexAction
        _sylius:
            template: SyliusBackendBundle:Option:index.html.twig
            sortable: true
            sorting:
                name: desc

sylius_backend_option_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.option:createAction
        _sylius:
            template: SyliusBackendBundle:Option:create.html.twig
            redirect: sylius_backend_option_index

sylius_backend_option_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.option:updateAction
        _sylius:
            template: SyliusBackendBundle:Option:update.html.twig
            redirect: sylius_backend_option_index

sylius_backend_option_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.option:deleteAction
        _sylius:
            redirect: sylius_backend_option_index
