sylius_backend_order_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            template: SyliusBackendBundle:Order:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting]

sylius_backend_order_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            template: SyliusBackendBundle:Order:create.html.twig
            redirect: sylius_backend_order_show

sylius_backend_order_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusBackendBundle:Order:update.html.twig
            redirect: sylius_backend_order_show

sylius_backend_order_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:deleteAction
        _sylius:
            redirect: sylius_backend_order_index

sylius_backend_order_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:filterFormAction
        _sylius:
            template: SyliusBackendBundle:Order:filterForm.html.twig

sylius_backend_order_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: SyliusBackendBundle:Order:show.html.twig

sylius_backend_order_by_user:
    pattern: /u/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexByUserAction
        _sylius:
            template: SyliusBackendBundle:Order:indexByUser.html.twig
            sortable: true
            sorting: { updatedAt: desc }
