sylius_backend_product_collection_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_collection:indexAction
        _sylius:
            template: SyliusBackendBundle:ProductCollection:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting]

sylius_backend_product_collection_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product_collection:createAction
        _sylius:
            template: SyliusBackendBundle:ProductCollection:create.html.twig
            redirect: sylius_backend_product_collection_show

sylius_backend_product_collection_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.product_collection:updateAction
        _sylius:
            template: SyliusBackendBundle:ProductCollection:update.html.twig
            redirect: sylius_backend_product_collection_show

sylius_backend_product_collection_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product_collection:deleteAction
        _sylius:
            redirect: sylius_backend_product_collection_index

sylius_backend_product_collection_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_collection:filterFormAction
        _sylius:
            template: SyliusBackendBundle:ProductCollection:filterForm.html.twig

sylius_backend_product_collection_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_collection:showAction
        _sylius:
            template: SyliusBackendBundle:ProductCollection:show.html.twig
