sylius_backend_promotion_rule_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.promotion_rule:deleteAction
        _sylius:
            redirect: referer
