sylius_backend_promotion_action_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.promotion_action:deleteAction
        _sylius:
            redirect: referer
