sylius_backend_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:indexAction
        _sylius:
            template: SyliusBackendBundle:User:index.html.twig
            filterable: true
            sortable: true
            sorting:
                id: desc

sylius_backend_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.user:updateAction
        _sylius:
            template: SyliusBackendBundle:User:update.html.twig
            redirect: sylius_backend_user_show
            form: fos_user_admin
            
sylius_backend_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.user:deleteAction
        _sylius:
            redirect: sylius_backend_user_index

sylius_backend_user_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:showAction
        _sylius:
            template: SyliusBackendBundle:User:show.html.twig

sylius_backend_user_toggle_mayorista:
    pattern: /{id}/toogle-mayorista
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:toggleMayoristaAction
        _sylius:
            redirect: sylius_backend_user_index