pigalle:
    resource: "@PigalleBundle/Resources/config/routing/main.yml"
    prefix:   /

gecko_newsletter:
    resource: "@GeckoNewsletterBundle/Resources/config/routing/main.yml"
    prefix:   /
    
sylius_backend_index:
    path:     /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
        
sylius_backend:
    resource: "@SyliusBackendBundle/Resources/config/routing/main.yml"
    prefix:   /admin
    
sylius_installer:
    resource: @SyliusInstallerBundle/Resources/config/routing.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_mayorista_security_login:
    pattern:  /mayorista/login
    defaults: { _controller: FOSUserBundle:Registration:registerMayorista }

fos_user_mayorista_security_check:
    pattern:  /mayorista/login_check
    defaults: { _controller: FOSUserBundle:Security:check }    
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /cuenta/perfil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /registro

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /cuenta
