gecko_newsletter_subscriber_subscribe:
    pattern: /suscribirse
    defaults: { _controller: gecko_newsletter.controller.subscriber:subscribeAction }
    
gecko_newsletter_subscriber_confirm:
    pattern: /suscribirse/confirmar/{token}
    defaults: { _controller: gecko_newsletter.controller.subscriber:confirmAction }
    
gecko_newsletter_subscriber_unsubscribe:
    pattern: /desuscribirse/{token}
    defaults: { _controller: gecko_newsletter.controller.subscriber:unsubscribeAction }  