parameters:
    sylius_backend.controller.dashboard.class: Gecko\SyliusBackendBundle\Controller\DashboardController
    sylius_backend.menu_builder.class: Gecko\SyliusBackendBundle\Menu\MenuBuilder
    
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    sylius_backend.controller.dashboard:
        class: %sylius_backend.controller.dashboard.class%
        calls:
            - [setContainer, [@service_container]]
        
    sylius_backend.menu_builder:
        class: %sylius_backend.menu_builder.class%
        arguments: [@knp_menu.factory, @security.context, @translator]
        
    sylius_backend.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: sylius_backend.menu_builder
        factory_method: createMainMenu
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: sylius_backend.menu.main }
    
    sylius_backend.menu.main_account:
        class: Knp\Menu\MenuItem
        factory_service: sylius_backend.menu_builder
        factory_method: createMainMenuAccount
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: sylius_backend.menu.main_account }
                    
    sylius_backend.menu.dashboard:
        class: Knp\Menu\MenuItem
        factory_service: sylius_backend.menu_builder
        factory_method: createDashboardMenu
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: sylius_backend.menu.dashboard }