gecko_newsletter_backend_subscriber_list_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: gecko_newsletter.controller.subscriber_list:indexAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/SubscriberList:index.html.twig

gecko_newsletter_backend_subscriber_list_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: gecko_newsletter.controller.subscriber_list:createAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/SubscriberList:create.html.twig
            redirect: gecko_newsletter_backend_subscriber_list_index

gecko_newsletter_backend_subscriber_list_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: gecko_newsletter.controller.subscriber_list:updateAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/SubscriberList:update.html.twig
            redirect: gecko_newsletter_backend_subscriber_list_index

gecko_newsletter_backend_subscriber_list_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: gecko_newsletter.controller.subscriber_list:deleteAction
        _sylius:
            redirect: gecko_newsletter_backend_subscriber_list_index