gecko_newsletter_backend_subscriber_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: gecko_newsletter.controller.subscriber:indexAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/Subscriber:index.html.twig

gecko_newsletter_backend_subscriber_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: gecko_newsletter.controller.subscriber:createAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/Subscriber:create.html.twig
            redirect: gecko_newsletter_backend_subscriber_index

gecko_newsletter_backend_subscriber_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: gecko_newsletter.controller.subscriber:updateAction
        _sylius:
            template: GeckoNewsletterBundle:Backend/Subscriber:update.html.twig
            redirect: gecko_newsletter_backend_subscriber_index

gecko_newsletter_backend_subscriber_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: gecko_newsletter.controller.subscriber:deleteAction
        _sylius:
            redirect: gecko_newsletter_backend_subscriber_index