sylius_account_profile:
    pattern:  /
    defaults: { _controller: GeckoUserBundle:Profile:edit }
    
sylius_account_change_password:
    pattern:  /password
    defaults: { _controller: GeckoUserBundle:ChangePassword:changePassword }