sylius_account_profile:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Profile:edit }
    
sylius_account_change_password:
    pattern:  /password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }