sylius_checkout_start:
    pattern: /
    defaults: { _controller: sylius.controller.process:startAction, scenarioAlias: 'sylius_checkout' }

sylius_checkout_display:
    pattern: /{stepName}
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout' }

sylius_checkout_forward:
    pattern: /{stepName}/forward
    defaults: { _controller: sylius.controller.process:forwardAction, scenarioAlias: 'sylius_checkout' }

sylius_checkout_security:
    pattern: /login
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout', 'stepName': 'login' }

sylius_checkout_addressing:
    pattern: /direccion
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout', 'stepName': 'direccion' }

sylius_checkout_shipping:
    pattern: /envio
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout', 'stepName': 'envio' }

sylius_checkout_payment:
    pattern: /metodo-de-pago
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout', 'stepName': 'metodo-de-pago' }

sylius_checkout_finalize:
    pattern: /resumen
    defaults: { _controller: sylius.controller.process:displayAction, scenarioAlias: 'sylius_checkout', 'stepName': 'resumen' }
