pigalle_homepage:
    pattern:        /
    defaults:       { _controller: PigalleBundle:Main:index }

pigalle_la_marca:
    pattern:        /la-marca
    defaults:       { _controller: PigalleBundle:Main:laMarca }

pigalle_locales:
    pattern:        /locales
    defaults:       { _controller: PigalleBundle:Main:locales }
        
sylius_product:
    resource: @PigalleBundle/Resources/config/routing/product.yml
    prefix:   /online-store

sylius_cart:
    resource: @PigalleBundle/Resources/config/routing/cart.yml
        
sylius_account:
    resource: @PigalleBundle/Resources/config/routing/account.yml
    prefix: /mi-cuenta
    
sylius_checkout:
    resource: @PigalleBundle/Resources/config/routing/checkout.yml
    prefix: /checkout

sylius_province_choice_form:
    pattern: /province/choice-form
    defaults:
        _controller: sylius.controller.province:choiceFormAction

#sylius_partial:
#    resource: @SyliusWebBundle/Resources/config/routing/partial/main.yml
#    prefix: /_partial

_imagine:
    resource: .
    type:     imagine