pigalle_homepage:
    pattern:        /
    defaults:       { _controller: PigalleBundle:Main:index }

pigalle_product_show:
    pattern:        /p/{slug}
    _controller:    sylius.controller.product:showAction
        _sylius:
            template: PigalleBundle:Product:show.html.twig
            criteria: {slug: $slug}
            
#sylius_province_choice_form:
#    pattern: /province/choice-form
#    defaults:
#        _controller: sylius.controller.province:choiceFormAction

#sylius_partial:
#    resource: @SyliusWebBundle/Resources/config/routing/partial/main.yml
#    prefix: /_partial

#_imagine:
#    resource: .
#    type:     imagine
