parameters:
#    gecko_user.example.class: Gecko\UserBundle\Example

services:
#    gecko_user.example:
#        class: %gecko_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
