parameters:
#    gecko_user.example.class: Gecko\UserBundle\Example

services:
    gecko_user.registration.form.type:
        class: Gecko\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_registration }
