parameters:
#    pigalle.example.class: Gecko\PigalleBundle\Example

services:
    pigalle.twig.price_extension:
        class: Gecko\PigalleBundle\Twig\PriceExtension
        tags:
            - { name: twig.extension }
