parameters:
#    pigalle.example.class: Gecko\PigalleBundle\Example

services:
#    pigalle.example:
#        class: %pigalle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
