parameters:
    pigalle.menu_builder.class: Gecko\PigalleBundle\Menu\MenuBuilder

services:
    pigalle.twig.price_extension:
        class: Gecko\PigalleBundle\Twig\PriceExtension
        tags:
            - { name: twig.extension }

    pigalle.profile.form.type:
        class: Gecko\PigalleBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sylius_user_profile }
            
    pigalle.pigalle_slide.form.type:
        class: Gecko\PigalleBundle\Form\Type\PigalleSlideType
        tags:
            - { name: form.type, alias: sylius_pigalle_slide }
    
    pigalle.product_collection.form.type:
        class: Gecko\PigalleBundle\Form\Type\ProductCollectionType
        tags:
            - { name: form.type, alias: sylius_product_collection }
            
    pigalle.product_collection_image.form.type:
        class: Gecko\PigalleBundle\Form\Type\ProductCollectionImageType
        arguments: [Gecko\PigalleBundle\Entity\ProductCollectionImage]
        tags:
            - { name: form.type, alias: sylius_product_collection_image }
            
    pigalle.controller.mayorista:
        class: Gecko\PigalleBundle\Controller\MayoristaController
        arguments: [sylius, product_collection, PigalleBundle:ProductCollection]
        calls:
          - [ setContainer, ["@service_container"] ]
          
    pigalle.menu_builder:
        class: %pigalle.menu_builder.class%
        arguments: [@knp_menu.factory, @security.context, @translator]
        calls:
          - [ setContainer, ["@service_container"] ]
        
    pigalle.menu.main_left:
        class: Knp\Menu\MenuItem
        factory_service: pigalle.menu_builder
        factory_method: createMainMenuLeft
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: pigalle.menu.main_left }
            
    pigalle.menu.main_right:
        class: Knp\Menu\MenuItem
        factory_service: pigalle.menu_builder
        factory_method: createMainMenuRight
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: pigalle.menu.main_right }
            
    pigalle.menu.account:
        class: Knp\Menu\MenuItem
        factory_service: pigalle.menu_builder
        factory_method: createAccountMenu
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: pigalle.menu.account }
  
    pigalle.menu.user:
        class: Knp\Menu\MenuItem
        factory_service: pigalle.menu_builder
        factory_method: createUserMenu
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: pigalle.menu.user }
            
    pigalle.menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: pigalle.menu_builder
        factory_method: createFooterMenu
        scope: request
        arguments: [@request]
        tags:
            -  { name: knp_menu.menu, alias: pigalle.menu.footer }