Gecko\NewsletterBundle\Entity\Subscriber:
    type: entity
    table: gecko_subscriber
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fullname:
            column: fullname
            type: string
            nullable: true
        email:
            column: email
            type: string
            unique: true
        enabled:
            column: enabled
            type: boolean
        confirmationToken:
            column: token
            type: string
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update